name: Deploy to Server via SFTP

on:
  push:
    branches:
      - main 

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # Cài đặt uv để có thể sử dụng lệnh uv export
      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          enable-cache: true

      # Xuất file requirements.txt trước khi upload
      - name: Export requirements
        run: uv export --format requirements-txt -o requirements.txt

      - name: Deploy via SFTP
        uses: wlixcc/SFTP-Deploy-Action@v1.2.4
        with:
          username: ${{ secrets.SFTP_USERNAME }}
          server: ${{ secrets.SFTP_HOST }}
          port: ${{ secrets.SFTP_PORT }}
          password: ${{ secrets.SFTP_PASSWORD }} 
          
          # Upload toàn bộ nội dung (bao gồm cả requirements.txt vừa tạo)
          local_path: './*' 
          
          # Đừng quên bỏ comment và điền đường dẫn thực tế trên server của bạn
          # remote_path: '/var/www/my-project'
          remote_path: '/'
          
          sftp_only: true
          # delete_remote_files: false
          # exclude: |
          #   .git*
          #   .github*
          #   __pycache__*
          #   venv*
          #   .python-version
          #   .uv